apiVersion: argoproj.io/v1alpha1
kind: WorkflowTemplate
metadata:
  name: mclr-rates # executable id, must be unique across all your workflows (YAML files), please modify this to any value (e.g. code-pipeline-12345) if you are not the only user of your SAP AI Core instance.
  annotations:
    scenarios.ai.sap.com/description: "Tutorial to add custom code to SAP AI Core"
    scenarios.ai.sap.com/name: "Mclr Rates Code (Tutorial)- New"
    executables.ai.sap.com/description: "Trains model on previous years mclr rates"
    executables.ai.sap.com/name: "Mclr Rates Prediction - New"
  labels:
    scenarios.ai.sap.com/id: "learning-code"
    ai.sap.com/version: "1.0"
spec:
  imagePullSecrets:
    - name: mclrnew # your docker registry secret
  entrypoint: mypipeline
  templates:
  - name: mypipeline
    steps:
    - - name: mypredictor
        template: mycodeblock2

  - name: mycodeblock2
    container:
      image: docker.io/dhwani108/mclr-rates-new:01 # Your docker image name
      command: ["/bin/sh", "-c"]
      args:
        - "python /app/src/main.py"
