apiVersion: argoproj.io/v1alpha1
kind: WorkflowTemplate
metadata:
  name: test-pipeline # executable id, must be unique across all your workflows (YAML files), please modify this to any value (e.g. code-pipeline-12345) if you are not the only user of your SAP AI Core instance.
  annotations:
    scenarios.ai.sap.com/description: "Test Code for Prediction"
    scenarios.ai.sap.com/name: "Test Code"
    executables.ai.sap.com/description: "Test Code for Prediction"
    executables.ai.sap.com/name: "Test Code Execution"
  labels:
    scenarios.ai.sap.com/id: "learning-code"
    ai.sap.com/version: "1.0"
spec:
  imagePullSecrets:
    - name: testcode # your docker registry secret
  entrypoint: mypipeline
  templates:
  - name: mypipeline
    steps:
    - - name: mypredictor
        template: mycodeblocktest

  - name: testcode
    container:
      image: docker.io/dhwani108/test-code:01 # Your docker image name
      command: ["/bin/sh", "-c"]
      args:
        - "python /app/src/main.py"

