apiVersion: argoproj.io/v1alpha1
kind: WorkflowTemplate
metadata:
  name: test-pipeline
  annotations:
    scenarios.ai.sap.com/description: "Test Code for Prediction"
    scenarios.ai.sap.com/name: "Test Code"
    executables.ai.sap.com/description: "Test Code for Prediction"
    executables.ai.sap.com/name: "Test Code Execution"
  labels:
    scenarios.ai.sap.com/id: "learning-code"
    ai.sap.com/version: "7.0"
spec:
  imagePullSecrets:
    - name: testcode
  entrypoint: mypipeline
  templates:
  - name: mypipeline
    steps:
    - - name: mypredictor
        template: testcode  # Fixed template reference

  - name: testcode  # This is the template definition you are referencing
    container:
      image: docker.io/dhwani108/test-code:07
      command: ["/bin/sh", "-c"]
      args:
        - "python /app/src/main.py"
